# Generated by Django 3.0.3 on 2020-04-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200426_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_sec',
            name='sec_group',
            field=models.CharField(choices=[('normal', 'ปก'), ('special', 'เป'), ('iup', 'IUP')], default='aa', max_length=10),
            preserve_default=False,
        ),
    ]
