# Generated by Django 3.0.3 on 2020-04-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sub_sec_sec_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_dt',
            name='dt_day2',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class_dt',
            name='dt_time2',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
