# Generated by Django 3.0.3 on 2020-05-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200501_0733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='room',
            new_name='room_db',
        ),
    ]
