# Generated by Django 3.0.3 on 2020-04-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200427_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='update_date',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date_str', models.CharField(max_length=255)),
            ],
        ),
    ]
