# Generated by Django 3.0.3 on 2020-05-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('room_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('room_amount', models.IntegerField()),
            ],
        ),
    ]
